=== ccnicholls99/ptekwpdev/app/config/schema/app.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "app.schema.json",
  "title": "ptekwpdev app.json schema",
  "type": "object",

  "required": [
    "app_key",
    "app_base",
    "config_base",
    "project_base",
    "backend_network",
    "secrets",
    "database",
    "assets",
    "wordpress_defaults"
  ],

  "properties": {
    "app_key": {
      "type": "string"
    },

    "app_base": {
      "type": "string"
    },

    "config_base": {
      "type": "string"
    },

    "project_base": {
      "type": "string"
    },

    "backend_network": {
      "type": "string"
    },

    "secrets": {
      "type": "object",
      "required": ["sqldb_root", "sqldb_root_pass"],
      "properties": {
        "sqldb_root": { "type": "string" },
        "sqldb_root_pass": { "type": "string" }
      },
      "additionalProperties": false
    },

    "database": {
      "type": "object",
      "required": [
        "sqldb_port",
        "sqldb_image",
        "sqldb_version",
        "sqladmin_image",
        "sqladmin_version",
        "sqladmin_port"
      ],
      "properties": {
        "sqldb_port": { "type": "string" },
        "sqldb_image": { "type": "string" },
        "sqldb_version": { "type": "string" },
        "sqladmin_image": { "type": "string" },
        "sqladmin_version": { "type": "string" },
        "sqladmin_port": { "type": "string" }
      },
      "additionalProperties": false
    },

    "assets": {
      "type": "object",
      "required": ["container", "root_path"],
      "properties": {
        "container": { "type": "string" },
        "root_path": { "type": "string" }
      },
      "additionalProperties": false
    },

    "wordpress_defaults": {
      "type": "object",
      "required": ["image", "php_version", "port", "ssl_port"],
      "properties": {
        "image": { "type": "string" },
        "php_version": { "type": "string" },
        "port": { "type": "integer" },
        "ssl_port": { "type": "string" }
      },
      "additionalProperties": false
    }
  },

  "additionalProperties": false
}

=== ccnicholls99/ptekwpdev/app/config/schema/app.tpl.json
{
  "app_key": "",
  "app_base": "",
  "config_base": "",
  "project_base": "",

  "backend_network": "",

  "secrets": {
    "sqldb_root": "",
    "sqldb_root_pass": ""
  },

  "database": {
    "sqldb_port": "",
    "sqldb_image": "",
    "sqldb_version": "",

    "sqladmin_image": "",
    "sqladmin_version": "",
    "sqladmin_port": ""
  },

  "assets": {
    "container": "",
    "root_path": ""
  },

  "wordpress_defaults": {
    "image": "",
    "php_version": "",
    "port": -1,
    "ssl_port": ""
  }
}

=== ccnicholls99/ptekwpdev/app/config/app.json
{
  "app_key": "ptekwpdev",
  "app_base": "/home/ccnicholls/projects/ptekwpdev",
  "config_base": "/home/ccnicholls/.ptekwpdev",
  "project_base": "/home/ccnicholls/ptekwpdev_repo",

  "backend_network": "ptekwpdev_backend",

  "secrets": {
    "sqldb_root": "root",
    "sqldb_root_pass": "v67ZOe7boEA7WjMglVCDsOkDoZgV1Nrj"
  },

  "database": {
    "sqldb_port": "3306",
    "sqldb_image": "mariadb",
    "sqldb_version": "10.5",

    "sqladmin_image": "phpmyadmin/phpmyadmin",
    "sqladmin_version": "latest",
    "sqladmin_port": "5211"
  },

  "assets": {
    "container": "ptekwpdev_assets",
    "root_path": "/usr/src/ptekwpdev/assets"
  },

  "wordpress_defaults": {
    "image": "wordpress:latest",
    "php_version": "8.2",
    "port": 8080,
    "ssl_port": "8443"
  }
}
